services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubsu -d kubsu"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # для постоянного хранения данных
      - db-data:/var/lib/postgresql/data
      # дамп прокатится единоразово при инициализации
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  api:
    build: ../
    restart: always
    depends_on:
      condition: service_healthy
    command: >
      sh -c '
        export PGPASSWORD=kubsu &&
        export DATABASE_URL=postgresql+psycopg2://kubsu:kubsu@db:5432/kubsu &&
        exec gunicorn src.main:app -k uvicorn.workers.UvicornWorker -w ${UVICORN_WORKERS:-2} -b 0.0.0.0:8115'
  
volumes:
  db-data:
