name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  prod:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U kubsu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        

      - name: Build Docker image
        run: docker build -t myapp:test .

      - name: Build test image
        run: docker build --target builder -t myapp:test .

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e PYTHONPATH=/app \
            myapp:test \
            pytest tests

             
      - name: Build prod image
        run: docker build -t myapp:latest .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          docker save myapp:latest | \
            ssh -o StrictHostKeyChecking=no \
                -p ${{ secrets.SSH_PORT }} \
                ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'set -eux podman load

            podman volume create pg_data || true
              podman run --replace -d \
          --name db \
          --network host \
          -e POSTGRES_DB=kubsu \
          -e POSTGRES_USER=kubsu \
          -e POSTGRES_PASSWORD=kubsu \
          -v pg_data:/var/lib/postgresql/data \
          postgres:16
            sleep 5
          podman run --replace -d \
          --name myapp \
          -p 80:8115 \
          -e DATABASE_URL=postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu \
          myapp:latest \
          uvicorn src.main:app --host 0.0.0.0 --port 8115'
